In [ ]:
import numpy as np
import torch

In [ ]:
t = torch.tensor([5.0, 10.0, 15.0],dtype=torch.float32,requires_grad=True)
v = t+5
vv =t*2

In [ ]:
np_array = np.array([[1, 4], [2, 3]])
t= torch.from_numpy(np_array).to(torch.float32)
t

In [ ]:
t = torch.zeros(3, 3)
t = torch.zeros(2, 2, dtype=torch.int32)
t

In [ ]:
torch.manual_seed(132)
rand = torch.rand(2, 2)
rand

In [ ]:
x = torch.ones(3,3, dtype=torch.int64)
empty_like_x = torch.empty_like(x)
empty_like_x

In [18]:
diag_elements = torch.tensor([5, 10, 15])
v = torch.diag(diag_elements)
v

tensor([[ 5,  0,  0],
        [ 0, 10,  0],
        [ 0,  0, 15]])

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = torch.triu(a)
c = torch.tril(a)
print(a)
print(v)
print(c)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]])
tensor([[1, 0, 0],
        [4, 5, 0],
        [7, 8, 9]])


: 